apiVersion: v1
kind: Service
metadata:
  name: otel-lgtm
spec:
  selector:
    app: otel-lgtm
  ports:
    - name: otlp-grpc
      port: 4317
      targetPort: otlp-grpc
    - name: otlp-http
      port: 4318
      targetPort: otlp-http
    - name: grafana
      port: 3000
      targetPort: grafana
